[build]
  functions = 'functions'

[[redirects]]
  from = '/api'
  to = '/.netlify/functions/api'
  status = 200

[[redirects]]
  from = '/docs'
  to = 'https://icjia-arrest-explorer-docs.netlify.app'
  status = 200

[[redirects]]
  from = '/*'
  to = '/index.html'
  status = 200