[build]
  functions = 'functions'

[[redirects]]
  from = '/api'
  to = '/.netlify/functions/api'
  status = 200

[[redirects]]
  from = '/docs'
  to = 'https://brilliant-kitten-33c85a.netlify.app'
  status = 200

[[redirects]]
  from = '/*'
  to = '/index.html'
  status = 200

