[build]
  functions = 'functions'

[[redirects]]
  from = '/arrestexplorer/api'
  to = 'https://festive-meitner-0c6e7d.netlify.app/.netlify/functions/api'
  status = 200

[[redirects]]
  from = '/*'
  to = '/index.html'
  status = 200